### ISSUE TITLE
I only get very few repositories for popular projects

### ISSUE THREAD

**Issue by fabioespinosa** [github-tooling/ghtopdep#11]
Don't know what i'm doing wrong but if I do:

`ghtopdep https://github.com/zeit/next.js`

I get:
```
| url                                |   stars |
|------------------------------------|---------|
| https://github.com/volny/dotconfig |      26 |
found 42 repositories others repositories are private
found 9 repositories with more than zero star
```

**Comment by andriyor** [comment]
This bug should be fixed in the new version `0.3.11`.
Can you confirm it?

Because of scraping popular project, such this takes a long time (40 min in my case) I added flag `--report` that will send results of scraping to lambda on AWS https://github.com/github-tooling/ghtopdep-backend and put to MongoDB collection with TTL seted to one month 
Also, I created a tiny frontend for that 
Source: https://github.com/github-tooling/ghtopdep-frontend-react
Site: https://ghtopdep.now.sh/
So with the flag --report  cli will send scraped data. If it doesn't exist on mongo and receive if it already exists
